set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Temux styling
set-option -sa terminal-override ",xterm*:Tc" # Enable true color
set -g status-style 'bg=#333333 fg=#ffc4ea' # Status bar
# Pane borders
set -g pane-border-lines single
set -g pane-border-style fg=#333333
set -g pane-active-border-style fg=#6707a6

# Start windows at panes at 1 not, 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/personal/dev/todo.md"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
