preload = /home/krieg/personal/anime/Luffy-Gear-5-.jpg
preload = /home/krieg/personal/anime/strategist_nami.jpg
preload = /home/krieg/personal/anime/Trahs_taste_Subway.jpg
preload = /home/krieg/personal/anime/Ciri.jpeg
preload = /home/krieg/personal/anime/Ciri.jpg
wallpaper = VGA-1,/home/krieg/personal/anime/Ciri.jpg

ipc = off
