# preload = /home/krieg/personal/anime/Luffy-Gear-5-.jpg
# preload = /home/krieg/personal/anime/Trahs_taste_Subway.jpg
# preload = /home/krieg/personal/anime/Ciri.jpeg
preload = /home/krieg/personal/anime/Ciri.jpg
# preload = /home/krieg/personal/anime/strategist_nami.jpg
preload = /home/krieg/personal/anime/Japan.jpg
# preload = /home/krieg/personal/anime/HornedJorny.jpg

# Main monitor
wallpaper {
    monitor = DP-5
    path = /home/krieg/personal/anime/Ciri.jpg
    fit_mode = cover
}
# Secondary monitor
wallpaper {
    monitor = DP-4
    path = /home/krieg/personal/anime/Japan.jpg
    fit_mode = cover
}

# Fallback for any other monitors
wallpaper {
    monitor = 
    path = /home/krieg/personal/anime/Ciri.jpg
}

ipc = on
